### PR TITLE
added all keys to io.KeyMap along with a small refactor

### PR DESCRIPTION
**Pull request by Julianiolo**
I added all keys to the io.KeyMap, with the define method used before, wich is now also used for setting the io.KeyData

### CODE REVIEW

**Comment by JeffM2501** [comment]
why "dual"? there is no "Single" so what is dual differentiating?

**Comment by JeffM2501** [comment]
Also it looks like the old code was setting all the raylib keys in the keymap.
The only refactor that I see that is needed is the removal of the old macro that is unused.
I'd prefer to not use macros if possible. Since everything is done in that one function, we can just have the expanded list of keys right there.

**Comment by Julianiolo** [comment]
Dual is differentiating between the other macro which only used raylib keys not both, but as you said I removed that "single" macro, so I guess you could remove the differentiation. 

This new macro is however used two times, once for setting the Keymap and once for setting KeyData.

**Comment by JeffM2501** [comment]
The keymap is now deprecated and should not be set
image

`KeysData `is the new way to handle that in ImGui. rlImGui has been updated to the new key API that was added in 1.87 and sets `IMGUI_DISABLE_OBSOLETE_KEYIO`. This means we can't call `KeyMap `and `KeysDown` anymore. it's all `KeysData`

I've removed the macro from current rlImGui code.

**Comment by Julianiolo** [comment]
Oh, It seems I was operating on either an old version of rlImGui or imgui which resultet in GetKeyName not working if KeyMap was not set. That however seems to be working now, and as you said, KeyMap is deprecated, so I guess this PR turned out to be kind of a fail lol.
Well sry for the time, and I think I'm gonna close this here. :)

**Comment by JeffM2501** [comment]
I'm working on changing the input system over to using the new events

**Pull request closed without merging**
