### PR TITLE
Change from "ImGuiIO. [Get/Set]ClipboardTextFn" to "ImGuiPlatformIO.Platform_[Get/Set]ClipboardTextFn"

### PR DESCRIPTION
**Pull request by rafin-dev**
In the new [Dear ImGui release](https://github.com/ocornut/imgui/releases/tag/v1.91.1), some IO handlers were changed from ImGuiIO to ImGuiPlatformIO.

Pull request changes: Replaces usage of the legacy API for the new one.

### CODE REVIEW

**Comment by rafin-dev** [comment]
*in (it's very embarrassing to leave a spelling mistake in the pull request, but oh well)

**Comment by rafin-dev** [comment]
wait, im stupid and somehow deleted the & synbol that makes ImGuiPlatformIO a reference, im really embarrassed, sorry for the inconvenience

**Comment by rafin-dev** [comment]
I know this is very little to really justify a pull request, but since I had to create a fork and fix this issue for my project, why not

**Comment by JeffM2501** [comment]
I already made the changes for platform IO a while ago in commit #76 50779c5e765b3a9fdd0cfae4497a37753b374f70
I think you had old code in your fork. If you had just rebased you would have picked them up.
This PR seems to just be whitespace differences and there is no reason to apply it.
But thanks for submiting it, had I not made the changes it would have been useful.

**Comment by rafin-dev** [comment]
sorry for the incovenience

**Pull request closed without merging**
